/**
 * Collaborator flow invariants.
 *
 * The matrícula (employeeCode) is auto-generated by the ms-user
 * pre-save hook (CustomerUsers.js: `A` + 7 padded digits). The
 * frontend MUST NOT require it on create and MUST surface it on
 * list + edit. These tests lock those contracts so a schema tweak
 * can't silently break a field the operator relies on for payroll.
 */

import { describe, it, expect } from 'vitest';
import {
  collaboratorFormSchema,
  DEFAULT_COLLABORATOR_VALUES,
  type CollaboratorFormValues,
} from '@/features/collaborators/schemas';

describe('collaborator form schema', () => {
  function validPayload(overrides: Partial<CollaboratorFormValues> = {}) {
    return {
      ...DEFAULT_COLLABORATOR_VALUES,
      firstName: 'Ana',
      lastName: 'Silva',
      email: 'ana.silva@example.com',
      username: 'ana.silva',
      password: 'Strong#Pass1',
      account: '64b9a1f1f1f1f1f1f1f1f1f1',
      client: '64b9a2f2f2f2f2f2f2f2f2f2',
      site: '64b9a3f3f3f3f3f3f3f3f3f3',
      ...overrides,
    };
  }

  it('accepts a create payload WITHOUT employeeCode (backend mints it)', () => {
    const parsed = collaboratorFormSchema.safeParse(validPayload());
    expect(parsed.success).toBe(true);
    if (parsed.success) {
      expect(parsed.data.customerUser.employeeCode).toBeUndefined();
    }
  });

  it('accepts an edit payload WITH a pre-existing employeeCode', () => {
    const parsed = collaboratorFormSchema.safeParse(
      validPayload({
        _id: '64b9a4f4f4f4f4f4f4f4f4f4',
        password: '',
        customerUser: {
          subtype: 'VIGILANT',
          status: 'ACTIVE',
          employeeCode: 'A0001042',
        },
      }),
    );
    expect(parsed.success).toBe(true);
  });

  it('rejects a create payload without password', () => {
    const parsed = collaboratorFormSchema.safeParse(
      validPayload({ password: '' }),
    );
    expect(parsed.success).toBe(false);
  });

  it('allows an edit payload without password (server keeps the old hash)', () => {
    const parsed = collaboratorFormSchema.safeParse(
      validPayload({ _id: '64b9a4f4f4f4f4f4f4f4f4f4', password: '' }),
    );
    expect(parsed.success).toBe(true);
  });

  it('restricts subtype to VIGILANT | SUPERVISOR (no admin smuggling)', () => {
    const parsed = collaboratorFormSchema.safeParse(
      validPayload({
        customerUser: {
          subtype: 'ADMIN' as unknown as 'VIGILANT',
          status: 'ACTIVE',
        },
      }),
    );
    expect(parsed.success).toBe(false);
  });
});

describe('i18n', () => {
  it('matricula label + auto-gen hint exist in every locale', async () => {
    const locales = ['pt', 'en', 'es', 'ja', 'zh'] as const;
    for (const l of locales) {
      const bundle = (await import(`@/messages/${l}.json`)).default as Record<
        string,
        unknown
      >;
      const collab = (bundle.collaborators ?? {}) as Record<string, unknown>;
      expect(typeof collab.employeeCode).toBe('string');
      expect((collab.employeeCode as string).length).toBeGreaterThan(0);
      expect(typeof collab.employeeCodeAutoGenerated).toBe('string');
      expect((collab.employeeCodeAutoGenerated as string).length).toBeGreaterThan(0);
    }
  });
});
